# backend/app/services/shotlist_generation_service.py

"""
Shotlist generation service. Reads screenplay content and scene data from the
database, calls AI with structured output to generate a complete shotlist, and
merges results into the database with smart protection for user-edited shots.

Plan 26-01 added user_modified/ai_generated columns. Plan 26-02 builds the
full generation pipeline: context builder, AI caller, and smart merge.
"""

import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from ..models import database
from .ai_provider import chat_completion_structured

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Pydantic structured output models (passed to chat_completion_structured)
# ---------------------------------------------------------------------------

class GeneratedShot(BaseModel):
    """A single shot generated by the AI cinematographer."""
    scene_index: int = Field(
        description="1-based index of the scene this shot belongs to"
    )
    shot_size: str = Field(
        default="",
        description="e.g., Wide, Medium, Close-Up, Extreme Close-Up"
    )
    camera_angle: str = Field(
        default="",
        description="e.g., Eye Level, Low Angle, High Angle, Dutch"
    )
    camera_movement: str = Field(
        default="",
        description="e.g., Static, Pan, Tilt, Dolly, Tracking, Crane"
    )
    description: str = Field(
        default="",
        description="What the camera sees in this shot"
    )
    action: str = Field(
        default="",
        description="What happens during this shot"
    )
    script_excerpt: str = Field(
        default="",
        description="The specific passage from the script this shot covers"
    )


class ShotlistGenerationResponse(BaseModel):
    """Complete shotlist generation result from AI."""
    shots: List[GeneratedShot]


# ---------------------------------------------------------------------------
# Internal data-passing dataclass
# ---------------------------------------------------------------------------

@dataclass
class ShotlistContext:
    """All data needed for a shotlist generation AI call."""
    screenplay_texts: List[str] = field(default_factory=list)
    scene_summaries: List[dict] = field(default_factory=list)
    project_title: str = ""
    existing_user_shots: int = 0


# ---------------------------------------------------------------------------
# Generation system prompt
# ---------------------------------------------------------------------------

GENERATION_SYSTEM_PROMPT = """You are a professional cinematographer creating a detailed shotlist for production.

Your task is to analyze the provided screenplay content and scene breakdowns, then generate a comprehensive shotlist that covers every scene.

SHOT ORDERING RULES:
1. For each scene, start with establishing/wide shots to orient the viewer
2. Follow with medium shots for dialogue and interaction coverage
3. Then close-ups for emotional beats and important details
4. Action shots come before reaction shots
5. Maintain a logical cinematic flow within each scene

FIELD REQUIREMENTS (every shot MUST have ALL of these non-empty):
- shot_size: The framing (e.g., "Wide", "Medium", "Medium Close-Up", "Close-Up", "Extreme Close-Up", "Over-the-Shoulder")
- camera_angle: The vertical angle (e.g., "Eye Level", "Low Angle", "High Angle", "Dutch Angle", "Bird's Eye", "Worm's Eye")
- camera_movement: How the camera moves (e.g., "Static", "Pan Left", "Pan Right", "Tilt Up", "Tilt Down", "Dolly In", "Dolly Out", "Tracking", "Crane Up", "Handheld", "Steadicam")
- description: What the camera sees in this shot (the visual composition)
- action: What happens during this shot (character actions, events)
- script_excerpt: A verbatim or near-verbatim passage from the provided screenplay text that this shot covers

SCENE ASSIGNMENT:
- Use the 1-based scene_index exactly as provided in the scene list
- Every scene should have at least one shot
- Typically 3-10 shots per scene; more for complex action sequences, fewer for simple dialogue

SCRIPT EXCERPT:
- Must be a verbatim or near-verbatim passage from the provided screenplay text
- Each shot should reference a specific part of the screenplay"""


# ---------------------------------------------------------------------------
# ShotlistGenerationService
# ---------------------------------------------------------------------------

class ShotlistGenerationService:
    """Service for AI-driven shotlist generation from screenplay content."""

    def _build_context(
        self, db: Session, project_id: UUID
    ) -> ShotlistContext:
        """
        Gather all data needed for shotlist generation from the database.

        Queries:
        - ScreenplayContent records for screenplay text
        - PhaseData(phase=scenes, subsection_key=scene_list) -> ListItem summaries
        - Project for title
        - Shot count where user_modified=True
        """
        # 1. Fetch screenplay content
        screenplays = db.query(database.ScreenplayContent).filter(
            database.ScreenplayContent.project_id == str(project_id)
        ).all()

        # 2. Fetch scene summaries from scenes.scene_list
        scene_summaries: List[dict] = []
        scenes_pd = db.query(database.PhaseData).filter(
            database.PhaseData.project_id == str(project_id),
            database.PhaseData.phase == "scenes",
            database.PhaseData.subsection_key == "scene_list",
        ).first()
        if scenes_pd:
            scene_items = db.query(database.ListItem).filter(
                database.ListItem.phase_data_id == str(scenes_pd.id)
            ).order_by(database.ListItem.sort_order).all()
            scene_summaries = [
                {
                    "id": str(li.id),
                    "summary": li.content.get("summary", f"Scene {li.sort_order + 1}"),
                    "sort_order": li.sort_order,
                }
                for li in scene_items
            ]

        # 3. Fetch project title
        project = db.query(database.Project).filter(
            database.Project.id == str(project_id)
        ).first()

        # 4. Count existing user-modified shots
        existing_user_shots = db.query(database.Shot).filter(
            database.Shot.project_id == str(project_id),
            database.Shot.user_modified == True,
        ).count()

        return ShotlistContext(
            screenplay_texts=[sc.content for sc in screenplays if sc.content],
            scene_summaries=scene_summaries,
            project_title=project.title if project else "",
            existing_user_shots=existing_user_shots,
        )

    def _build_user_prompt(self, ctx: ShotlistContext) -> str:
        """
        Format shotlist generation context into a user prompt for the AI.

        Scene indexing is 1-based (Scene 1, Scene 2, ...) so AI scene_index
        references in GeneratedShot map directly to position.
        """
        parts = [f"# Screenplay: {ctx.project_title}\n"]

        # Scene list with indices
        parts.append("## Scenes")
        for i, scene in enumerate(ctx.scene_summaries):
            parts.append(f"Scene {i + 1}: {scene['summary']}")
        parts.append("")

        # Full screenplay text (truncate at 50000 chars)
        parts.append("## Screenplay Content")
        combined_text = ""
        for text in ctx.screenplay_texts:
            combined_text += text + "\n---\n"
        if len(combined_text) > 50000:
            combined_text = combined_text[:50000] + "\n... [truncated]"
        parts.append(combined_text)

        # Footer
        parts.append("\nGenerate a complete shotlist covering all scenes.")

        # Note about existing user shots
        if ctx.existing_user_shots > 0:
            parts.append(
                f"Note: {ctx.existing_user_shots} user-edited shots already exist "
                f"and will be preserved. Generate shots to complement them."
            )

        return "\n".join(parts)

    async def _call_ai(self, ctx: ShotlistContext) -> ShotlistGenerationResponse:
        """Call AI with structured output to generate a shotlist."""
        messages = [
            {"role": "system", "content": GENERATION_SYSTEM_PROMPT},
            {"role": "user", "content": self._build_user_prompt(ctx)},
        ]
        return await chat_completion_structured(
            messages=messages,
            response_model=ShotlistGenerationResponse,
            temperature=0.3,
            max_tokens=16000,
        )

    def _map_scene_index_to_id(
        self, ctx: ShotlistContext, scene_index: int
    ) -> Optional[str]:
        """
        Convert 1-based scene_index from AI response to ListItem ID.

        AI returns 1-based indices; scene_summaries is 0-indexed.
        Invalid indices (out of range) return None with a warning.
        """
        zero_based = scene_index - 1
        if 0 <= zero_based < len(ctx.scene_summaries):
            return ctx.scene_summaries[zero_based]["id"]
        else:
            logger.warning(
                "Invalid scene_index %d (total scenes: %d) -- skipping",
                scene_index,
                len(ctx.scene_summaries),
            )
            return None

    def _merge_shots(
        self,
        db: Session,
        project_id: UUID,
        generated: List[GeneratedShot],
        ctx: ShotlistContext,
    ) -> dict:
        """
        Smart merge algorithm:
        1. Delete old AI-generated unmodified shots
        2. Preserve user-modified and manual user shots
        3. Insert new AI-generated shots
        4. Re-number sort_order within each scene
        """
        project_id_str = str(project_id)

        # 1. Query all existing shots for this project
        existing_shots = db.query(database.Shot).filter(
            database.Shot.project_id == project_id_str
        ).all()

        # 2. Partition: delete AI shots that haven't been user-modified
        deleted_count = 0
        preserved_shots: List[database.Shot] = []
        for shot in existing_shots:
            if shot.ai_generated and not shot.user_modified:
                db.delete(shot)
                deleted_count += 1
            else:
                preserved_shots.append(shot)

        db.flush()

        # 3. Track shot_number per scene for sequential numbering
        scene_shot_counters: Dict[str, int] = {}

        # 4. Insert new AI-generated shots
        created_count = 0
        new_shots: List[database.Shot] = []
        for gen_shot in generated:
            scene_id = self._map_scene_index_to_id(ctx, gen_shot.scene_index)
            if scene_id is None:
                continue

            # Increment shot_number per scene
            scene_key = scene_id
            if scene_key not in scene_shot_counters:
                scene_shot_counters[scene_key] = 1
            else:
                scene_shot_counters[scene_key] += 1

            new_shot = database.Shot(
                project_id=project_id_str,
                scene_item_id=scene_id,
                shot_number=scene_shot_counters[scene_key],
                script_text=gen_shot.script_excerpt,
                fields={
                    "shot_size": gen_shot.shot_size,
                    "camera_angle": gen_shot.camera_angle,
                    "camera_movement": gen_shot.camera_movement,
                    "description": gen_shot.description,
                    "action": gen_shot.action,
                },
                sort_order=0,  # Will be re-assigned below
                source="ai",
                ai_generated=True,
                user_modified=False,
            )
            db.add(new_shot)
            new_shots.append(new_shot)
            created_count += 1

        db.flush()

        # 5. Re-number sort_order within each scene
        # Group all remaining shots by scene_item_id
        scene_groups: Dict[Optional[str], List[database.Shot]] = {}
        all_shots = preserved_shots + new_shots
        for shot in all_shots:
            scene_key = str(shot.scene_item_id) if shot.scene_item_id else None
            if scene_key not in scene_groups:
                scene_groups[scene_key] = []
            scene_groups[scene_key].append(shot)

        # Within each group: user_modified shots keep relative order first, then AI shots
        for scene_key, shots_in_scene in scene_groups.items():
            user_shots = [s for s in shots_in_scene if s.user_modified or (not s.ai_generated)]
            ai_shots = [s for s in shots_in_scene if s.ai_generated and not s.user_modified]
            # Sort user shots by their existing sort_order
            user_shots.sort(key=lambda s: s.sort_order)
            ordered = user_shots + ai_shots
            for idx, shot in enumerate(ordered):
                shot.sort_order = idx

        return {
            "created": created_count,
            "deleted": deleted_count,
            "preserved": len(preserved_shots),
        }

    async def generate(self, db: Session, project_id: UUID) -> dict:
        """
        Full shotlist generation pipeline:
        1. Build context from database
        2. Validate prerequisites
        3. Call AI with structured output
        4. Execute smart merge
        5. Commit and return summary
        """
        try:
            # 1. Build context
            ctx = self._build_context(db, project_id)

            # 2. Validate -- must have screenplay content
            if not ctx.screenplay_texts:
                return {
                    "status": "error",
                    "message": "No screenplay content found",
                }

            # 3. Validate -- must have scenes
            if not ctx.scene_summaries:
                return {
                    "status": "error",
                    "message": "No scenes found. Add scenes before generating shotlist.",
                }

            # 4. Call AI
            response = await self._call_ai(ctx)

            # 5. Execute merge
            merge_result = self._merge_shots(db, project_id, response.shots, ctx)

            # 6. Commit
            db.commit()

            # 7. Return summary
            return {
                "status": "success",
                "shots_created": merge_result["created"],
                "shots_deleted": merge_result["deleted"],
                "shots_preserved": merge_result["preserved"],
            }

        except Exception as e:
            db.rollback()
            logger.error(
                "Shotlist generation failed for project %s: %s",
                project_id, e,
            )
            raise


# Module-level singleton
shotlist_generation_service = ShotlistGenerationService()
